# Generated by Django 5.2 on 2025-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_permissionchangelog_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
